name: pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest 

    steps: 

      - name: Copiar Arquivos do Repositório
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Instalar Poetry
        run: pipx install poetry

      - name: Instalar Dependências
        run: poetry install
      
      - name: Executar Testes
        run: poetry run task test 

    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}


      
